### ISSUE TITLE
Column value not shown on duplicate column names

### ISSUE THREAD

**Issue by ak8zs** [box/spout#521] opened 2017-12-13 14:33 UTC
kindly correct me if i missed this in you docs.

When using duplicate column names **writer** removing column values and replacing with next column value 
> in below example colA (second presence) value is overwrite by colD value

ColA | ColB | ColC | ColA | ColD
-- | -- | -- | -- | --
colA value | colB value | colC value | colD value |  
colA value | colB value | colC value | colD value |  
colA value | colB value | colC value | colD value |  

Thanks

**Comment by adrilo** [comment] 2017-12-13 15:55
Hello!
Spout does not care about column names. The header is just a regular row that you formatted as bold. There are also no special logic between rows.
If you're using an associative array with the column name as the key, that may be why you're seeing this. If not, please provide some code and/or examples so we can help you.

**Comment by ak8zs** [comment] 2017-12-14 07:07
Yes i am using associative array to write rows. and editing it no **numeric** solves the problem.

but i am confused if spout does not care about column names then why there is issue while using associative array.

**Comment by adrilo** [comment] 2017-12-14 10:19
I guess the problem is with the data you provide to Spout. If you have an array like this:
```
$data = [
  'colA' => [...],
  'colB' => [...],
  'colC' => [...],
  'colA' => [...],
];
```
then one of the "colA" will be overwritten by the other.

**Comment by adrilo** [comment] 2018-03-25 22:13
[Auto cleanup] Closing the issue

**Closed by adrilo** 2018-03-25 22:13 UTC
Labels: waiting for answer
