### ISSUE TITLE
Excel claiming the xlsx file is corrupt.

### ISSUE THREAD

**Issue by dipdill** [box/spout#318] opened 2016-09-27 20:40 UTC
I just updated my php to 5.6.25 and my Excel to 15.0.4849.1003 and now my spout box generate xlsx files don't open.  I keep getting a "We found a problem with some content in 'Filename'.  Do you want us to try to recover as much as we can?  If you trust the source of this workbook click Yes." popup message... and when I click Yes... I get a "The file is corrupt and cannot be opened" message.  Is there anything I can do to enable a trace to help resolve the issue.  Or if would you like a copy of the generated file I can provide that.

Thanks

**Comment by adrilo** [comment] 2016-09-27 22:38
Hi @dipdill! Can you please attach a copy of the generated file? This will help debugging your issue. Thanks!

**Comment by bevhost** [comment] 2016-09-27 23:28
I am see problems like this too.
[Staff-2015February.xlsx](https://github.com/box/spout/files/496818/Staff-2015February.xlsx)

**Comment by adrilo** [comment] 2016-09-28 03:16
Which version of Spout are you using? Did it work before and stopped working when you upgraded?

**Comment by adrilo** [comment] 2016-09-28 03:50
After unzipping and re-zipping the file you sent me @bevhost, it worked... I did not touch any file whatsoever. So my guess would be that the library you're using to zip the file may not work as it's supposed to work?!?!

**Comment by dipdill** [comment] 2016-09-28 13:58
Is there an easy way to tell what version of spout box I am using?  I have a version that i downloaded on 9/2/2016 and 9/27/2016.  Both have the same result.

**Comment by dipdill** [comment] 2016-09-28 15:52
Here is my file that I am trying to generate... just filled it with Dummy data for now to make sure I wasn't adding any special character that would break it.

[Export.xlsx](https://github.com/box/spout/files/498670/Export.xlsx)

If there is anything else you need from me to help troubleshoot this... let me know.  Thanks

**Comment by adrilo** [comment] 2016-09-28 17:08
@dipdill Unzipping your file fails...
```
$ unzip Export.xlsx
Archive:  Export.xlsx
warning [Export.xlsx]:  1269 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [Export.xlsx]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

So seems like a similar problem @bevhost has. There is something wrong with your zip library. Can you tell me which version of libzip you are using? `php -i | grep Libzip`

**Comment by dipdill** [comment] 2016-09-28 18:06
Libzip version => 1.1.2

**Comment by adrilo** [comment] 2016-09-28 18:09
Hmmm the Libzip versions we are using are 0.x. I'm wondering what changed since the bump to v1.

**Comment by bevhost** [comment] 2016-09-30 00:27
I am using php55-php-pecl-zip-1.13.4-1.el6.remi.x86_64 which is Libzip version 1.1.3
see https://pecl.php.net/package-changelog.php?package=zip

**Comment by adrilo** [comment] 2016-10-06 06:48
So I tried with PHP7 and libzip 1.1.2 and it works fine. @bevhost, do you know if the file creation has ever worked for you? Is it happening with all files or just this specific one?

**Comment by bevhost** [comment] 2016-10-06 08:35
Unfortunately I did all of my development and testing with LibreOffice on my Linux Desktop.
I didn't know there was a problem until other windows users reported it to me.
I did simplify the file a lot to see if it helped, but it did not.
I have installed php70 & php71, both use Libzip 1.1.3 and both still have the problem.

**Comment by bevhost** [comment] 2016-10-06 08:57
I created a really simple sheet and it generates ok and excel is happy
        $sheet = $writer->getCurrentSheet();
        $sheet->setName("SHEET 1");
        $writer->addRowWithStyle(["Apple","Banana","Cake","Drink","Egg"],$style);
        $writer->addRow([1,2,3,4,5]);
        $sheet = $writer->addNewSheetAndMakeItCurrent();
        $sheet->setName("SHEET 2");
        $writer->addRow([1,2,3,4,5]);
So I guess I need to play with it and work out what makes it go bad.

**Comment by adrilo** [comment] 2016-10-06 15:30
Yes, sorry I can't help more. If you ever find out what's wrong, can you please post your findings here? Thanks!

**Comment by Neo-Desktop** [comment] 2016-10-12 16:55
I've come to realize that if an empty sheet is generated, Excel will claim corruption. Libre Office will happily open it, however.

**Comment by adrilo** [comment] 2016-10-12 17:07
@Neo-Desktop Do you mind create a new issue for this? Although the same behavior is experienced, the root cause is definitely different.

**Comment by yshing** [comment] 2016-11-19 09:35
Same here... OK for really small xlsx files but larger.. but fail when generating files with more lines..

**Comment by adrilo** [comment] 2016-11-19 20:04
@yshing do you mind sharing some code? Or even better the generated file that is corrupted?

**Comment by kbond** [comment] 2016-11-21 14:31
I am also having this issue. I discovered it had to do with the length of a column. `32767` works fine but `32768` does not. See the test project I created for the code/samples here: https://github.com/kbond/spout-test

My Libzip version is `1.1.2` and other environment details are in the excel files.

**Comment by adrilo** [comment] 2016-11-21 18:17
@kbond, the 32767 characters max is an Excel limitation... See here: https://support.office.com/en-us/article/Excel-specifications-and-limits-16c69c74-3d6a-4aaf-ba35-e6eb276e8eaa (this is for Excel 2007 but also applies to more recent versions too).

Spout does not check for this limit, hence the error. Maybe a check should be added? I'm going to create a separate issue for this

**Comment by kbond** [comment] 2016-11-21 18:29
@adrilo ah, thanks for the info!

**Comment by manmoi01** [comment] 2016-11-23 03:38
@adrilo Hello I am using spout in the godaddy webhosting and the same problem is presented, godady uses php 5.4.19 and libzip 0.10.1. The xlsx file can not be opened in excel

**Comment by adrilo** [comment] 2016-11-23 04:12
@manmoi01 This problem can come from many things. Can you please send me the corrupted file so I can take a look?

**Comment by wyred** [comment] 2016-12-08 08:12
Has anyone managed to find the problem? I think I'm experiencing the same problem as well.

A small excel file with 2 sheets, about 50 rows on each sheet opens fine.
A large excel file with 2 sheets, about 2,000 rows on each sheet, the file cannot be opened. 

First sheet has 15 columns, second sheet has 42 columns.

Another thing I noticed is when I tried using PHPOffice/PHPExcel to export the same data, it generated a file with the file size of 644KB while the file generated using spout is 1.1MB.

Both files are generated in an Ubuntu environment, Libzip version => 1.1.2, PHP 7.0.8-2+ (I'm using Laravel Homestead) and opened using Numbers on macOS.

**Comment by adrilo** [comment] 2017-02-13 21:25
[CLEANUP] Closing issue as no answer was given in the last 3 months

**Closed by adrilo** 2017-02-13 21:25 UTC
Labels: bug

**Comment by retana** [comment] 2018-03-08 14:46
I replaced the xlsx version with an old one and the problem was solved, exactly this version:
[xlsx.zip](https://github.com/box/spout/files/1793566/xlsx.zip)

**Comment by hhren1984** [comment] 2019-05-24 16:06
99% is that don't set the content-length, eg: header("Content-Length: " . filesize($file_url));

**Comment by rondog** [comment] 2019-09-10 16:43
I know this thread is old, but I found the solution in another thread https://github.com/box/spout/issues/168#issuecomment-197276897

**Comment by japita-se** [comment] 2020-04-23 18:51
@rondog  
why the exit; instruction makes it work?!

**Comment by NemanjaMilosevic** [comment] 2021-12-22 09:45
My issue was that i was using WriterEntityFactory::createRowFromArray, with a 2D array.
