### ISSUE TITLE
Possible memory leak when reading files

### ISSUE THREAD

**Issue by rusakov92** [box/spout#373] opened 2017-01-06 09:58 UTC
Hello,

I'm using your library to read and write XLSX files and I noticed that some memory was not freed after the reading of a file is over. The PHP script and XLSX file that I'm using for testing [here](https://github.com/box/spout/files/689517/Archive.zip).

Before running the script please update the path to the file on line 8.

After you run the script in the console you will see that with every new instance of the reader the memory usage is greater than the previews one. The memory usage in the start of the script for me was around 3.75mb and I expect after the reader instance is destroyed to be again around 4mb of used memory and instead it is 30mb.

The script then runs one more time the test function to read again the file and this time in the end after the garbage collection cycle is called I get memory usage around 50mb.

Can you tell me if this is my fault or it is an issue from the library?

**Comment by adrilo** [comment] 2017-01-06 12:47
Hi @rusakov92, thanks for filing this issue. I ran your script on my computer and observed the same behavior:

```
$ php test.php
string(9) "Start 0.5"
string(10) "Read 15.75"
string(10) "Read 30.75"
string(10) "Read 45.75"
string(9) "Read 60.5"
string(9) "Read 75.5"
string(9) "Read 90.5"
string(11) "Read 105.25"
string(11) "Read 120.25"
string(17) "After close 26.25"
string(26) "After reader destroy 26.25"
string(10) "Read 26.25"
string(10) "Read 30.75"
string(10) "Read 45.75"
string(9) "Read 60.5"
string(9) "Read 75.5"
string(9) "Read 90.5"
string(11) "Read 105.25"
string(11) "Read 120.25"
string(16) "After close 48.5"
string(23) "After reader destroy 45"
```

This issue needs a deeper investigation to locate where the leaks are. @rusakov92, feel free to take a look at it if you can.

**Comment by rusakov92** [comment] 2017-01-06 12:54
Hi @adrilo, thanks for the update I'll try to look around if I have some free time.

**Comment by tuha305** [comment] 2018-05-22 16:32
Here is my result:
```
php7.0 test.php 
string(7) "Start 2"
string(6) "Read 8"
string(7) "Read 16"
string(7) "Read 22"
string(7) "Read 28"
string(7) "Read 36"
string(7) "Read 42"
string(7) "Read 48"
string(7) "Read 56"
string(14) "After close 56"
string(23) "After reader destroy 56"

string(7) "Read 56"
string(7) "Read 56"
string(7) "Read 56"
string(7) "Read 56"
string(7) "Read 56"
string(7) "Read 56"
string(7) "Read 56"
string(7) "Read 56"
string(14) "After close 56"
string(23) "After reader destroy 56"
```

I supposed these lines of code cause the memory leak:
```
        $data[] = [
            'title' => $sheet->getName(),
            'data' => iterator_to_array($sheet->getRowIterator(), false),
        ];
```

When you assign null to `$data`, it simply destroys the variable reference to the data.  
The data still exists in memory and PHP sees the memory as in use despite no longer having a pointer to it.

**Comment by adrilo** [comment] 2018-05-22 21:29
The use of `gc_collect_cycles` should free the memory when it finds "zombie" references. So in our case, the value in "After reader destroy" log should be lower that what's before.

**Comment by tuha305** [comment] 2018-05-22 23:45
I defined myself `dosomething($title, $data)` function and replaced theses lines of code:
```
        $data[] = [
            'title' => $sheet->getName(),
            'data' => iterator_to_array($sheet->getRowIterator(), false),
        ];
```
with
```
        foreach ($sheet->getRowIterator() as $row) {
            dosomething($sheet->getName(), $row);
        }
```
then I ran the script again and didn't see any memory leaks.

**Comment by tuha305** [comment] 2018-05-22 23:58
I tested with a generator and got a small number of memory leak.

```
<?php

function read($file) {
    $fp = fopen($file, 'r');

    while (!feof($fp)) {
        yield fgetcsv($fp);
    }

    fclose($fp);

    var_dump('After close '.round(memory_get_usage(true)/1048576,2));
}

function test($file, &$data) {
    foreach (read($file) as $line) {
        $data[] = $line;

    }
    $data = null;
    var_dump('Read '.round(memory_get_usage(true)/1048576,2));
}


var_dump('Start '.round(memory_get_usage(true)/1048576,2));

$data = null;
test(dirname(__FILE__).'/1.csv', $data);
$data = null;

echo gc_collect_cycles() . "\n";
var_dump('After destroy '.round(memory_get_usage(true)/1048576,2));
```

it will not happen if I replace this assign `$data[] = $line` with a function call `dosomething($line)`.

It appears that `gc_collect_cycles` doesn't free the memory.

**Comment by adrilo** [comment] 2018-05-29 20:51
What's being displayed by your script? I'm especially interested in the `echo gc_collect_cycles()`.
Also, can you try disabling gc manually before starting your script, just in case? You can add `gc_disable();` at the beginning.

**Comment by pop-mihai** [comment] 2018-09-17 15:03
Same here, while testing a 100K XLSX File with 161 ROWS.

- PHP 7.2 Environment.
- gc_disable(); called at the beginning of the script.
- every 1000 Rows calling $row = null; gc_collect_cycles(); 
- gc_collect_cycles() returns 0.

First 1000 rows @ 6 mb
Second 1000 rows @ 10 mb
Third 1000 rows @ 18 mb
Next 1000 rows @ 34 mb
Next 4 chunks @ 34 mb
Next chunk @ 66 mb
Around the 43rd chunk @ 258 mb 
From the 72nd chunk all the way to the end: 514 MB

Total time to traverse this file was 1392 seconds !


`
gc_disable();
$reader = ReaderFactory::create(Type::XLSX);
$reader->open("./samples_template_100000.xlsx");
foreach ($reader->getSheetIterator() as $sheet) {
    foreach ($sheet->getRowIterator() as $row) {

        // tamper with the data.
        $row[] = 1;

        if (++$iteration % 1000 === 0) {
            \error_log("[EXCEL] Read row $iteration @ ".(memory_get_usage(true)/1024/1024));
            \error_log("[EXCEL] Collect Cycles Output: ". json_encode(gc_collect_cycles()));
        }
    }
}`


Here is the file we have tested with:
https://drive.google.com/file/d/1DbKD28u46BI761YjdsVelvjFux6YZJl1/view?usp=sharing

I find it somewhat odd that other libraries that we have tried to use got stuck with the same bottleneck: XLSX. Any help on this matter would is highly appreciated.

**Comment by pop-mihai** [comment] 2018-09-24 11:51
Any update on the above case gentlemen ?

**Comment by pop-mihai** [comment] 2018-10-24 08:59
With the little time I had available lately to allocate to this matter, after running **composer require box/spout** on a clean project and repeating my tests: I am unable to reproduce the memory leak no matter what i throw at it. I'm pretty sure nothing has changed on box/spout, but perhaps its dependencies got upgraded !?

**Comment by adrilo** [comment] 2018-11-02 10:29
@pop-mihai Nothing changed on the master branch indeed. `composer.lock` is committed in the repo, so dependencies should be locked. That's weird...

**Comment by pop-mihai** [comment] 2018-11-02 15:14
@adrilo Is it possible at all that it is related to this: https://pecl.php.net/package-changelog.php?package=zip&release=1.15.4 ?

**Comment by adrilo** [comment] 2018-11-02 16:29
Aaaaaah that's probably it!! Thanks for digging into the changelog :)
I can't repro the issue either so that's a good news !

**Closed by adrilo** 2018-11-02 16:29 UTC
Labels: bug, help wanted
