### ISSUE TITLE
Can't support xlsx file created by WPS Office(an office software likes MS office, almost only used in China)

### ISSUE THREAD

**Issue by momopluto** [box/spout#254] opened 2016-06-15 08:35 UTC
For some reason, my program should read the data from xlsx file which creates by WPS Office.

I was disturbed by the difference between WPS Office and MS office.

At first, all my test xlsx file was from WPS. I got the error as follow.

> <b>Fatal error</b>:  Uncaught exception 'Box\Spout\Common\Exception\IOException' with message 'Could not open C:/Users/sf/Desktop/Book1.xlsx for reading! (Index invalid or out of range)' in D:\AppServ\www\exp\spout\src\Spout\Reader\AbstractReader.php:105
> Stack trace:
> #0 D:\AppServ\www\exp\test_spout.php(22): Box\Spout\Reader\AbstractReader-&gt;open('C:/Users/sf/Des...')
> #1 {main}
>   thrown in <b>D:\AppServ\www\exp\spout\src\Spout\Reader\AbstractReader.php</b> on line <b>105</b><br />

But after I transfer Book1.xlsx from WPS one to MS one, I get the result I want!

I really want to use the library, to low the memory usage(That attract me!).

Moreover, WPS Office has enough user in China, just like MS Office in other country, I think.

So, if you could improve the library to support xlsx file from WPS, it will make Spout be more popular in Chinese developer.
And personally, I will be very thankful if you could do that.

**Comment by madflow** [comment] 2016-06-15 09:07
Please attach a not working file created with WPS Office for testing.

**Comment by momopluto** [comment] 2016-06-16 03:11
[MS_Spout_test.xlsx](https://github.com/box/spout/files/317608/MS_Spout_test.xlsx)
[WPS_Spout_test.xlsx](https://github.com/box/spout/files/317609/WPS_Spout_test.xlsx)

MS_Spout_test.xlsx, works.
WPS_Spout_test.xlsx, not.

ps:
You can download the [WPS Office](http://www.wps.cn/) from its wesite.

Thanks for your help!

**Comment by madflow** [comment] 2016-06-16 15:48
Okay I did a quick test on this one. The problem seems with the ```InMemoryStrategy```. When I hardcode the caching strategy to ```FileBasedStrategy``` - then the file is read.

The ```InMemoryStrategy``` uses a ```SplFixedArray``` as storage. Interestingly the  "Width" of the fixed array is calculated wrongly.

```
// $sharedStringsUniqueCount  is 0

     * @param int $sharedStringsUniqueCount Number of unique shared strings
     */
    public function __construct($sharedStringsUniqueCount)
    {
        $this->inMemoryCache = new \SplFixedArray($sharedStringsUniqueCount);
        $this->isCacheClosed = false;
    }
```

This is pretty deep in XML land - I commited a first failing test in a branch in my fork - Not sure if bug or not...

**Comment by adrilo** [comment] 2016-06-16 17:06
@momopluto I just pushed a fix. Please verify that the problem is now fixed for you. Thanks!

**Closed** 2016-06-16 17:06 UTC

**Comment by momopluto** [comment] 2016-06-17 09:31
Yes, it works.
Many thanks!
