### ISSUE TITLE
issue : In box spout,when reading cell with "&#Number" content but that content  "&#Number" is not shown.

### ISSUE THREAD

**Issue by ArokiaDasA** [box/spout#409] opened 2017-04-27 07:34 UTC
Hi,
When I try to read the cell values like "03-0129-1-HP LED 18.5& #34;19KA Monitor" using box spout.It writtens only "03-0129-1-HP LED 18.5''19KA Monitor" this value. The "&#34;" content is eliminated.
What Should I do?

In the above question don't use space between & and #. why I am using space is,in github without space between & and # is converted into blank.

**Comment by adrilo** [comment] 2017-04-28 00:28
@ArokiaDasA I just pushed a fix. Can you fetch the latest version and let me know if the problem is fixed? Thanks!

**Closed** 2017-04-28 00:27 UTC
