### ISSUE TITLE
Option to show datetimes with the original format

### ISSUE THREAD

**Issue by sangar82** [box/spout#330] opened 2016-10-13 13:49 UTC
Hi!
I've some problems when I process a xlsx with spanish dates.

I work with spanish dates like 'D-M-Y' (28-12-2017) or 'D/M/Y' (28/12/2017) and the setShouldFormatDates option is a headache for me.

There are any possibility to add an option to return the string that is showed in the xlsx when the cell is a date instead of return an object or the date in english format (or xlsx date format) ??

I need to extract the date with the original format, not with a different format or an object.

Thanks for this great package!

**Comment by sangar82** [comment] 2016-10-13 14:09
At this moment, my only solution to solve this is use a excel function. I create a new column  from the original column with dates with this function

````
=TEXT(B1;"DD-MM-AAAA")
````
where B1 is a cell with a date

**Comment by sangar82** [comment] 2016-10-13 20:16
I tried too change the cell format on Excel, but reading the cell sometimes output strange characters with spanish formats

**Comment by sangar82** [comment] 2016-10-14 07:24
With petit_barres.xlsx 
Date saved as 25/7/1982 and save with excel cell format 14/03/01
After read show: 7/25/1982 (Show format n-d-Y instead of d-m-Y)

With petit_guions.xlsx
Date saved as 25-7-1982 and save with excel cell format 14-03-01
After read show: 25-07-82;@ (Unexpected string ';@')

[petit_barres.xlsx](https://github.com/box/spout/files/528894/petit_barres.xlsx)
[petit_guions.xlsx](https://github.com/box/spout/files/528895/petit_guions.xlsx)

Hope this helps!

**Comment by adrilo** [comment] 2016-10-18 17:02
@sangar82 thanks for sending me these 2 files. It was really helpful and helped me find different problems regarding how Spout handles dates.

With dates saved as "14/03/01" that are displayed as "03/14/01", the issue is an environment issue. Your OS is configured to have dates displayed as "14/03/01" by default. Excel has been localized and basically take this format and assign it to its default short date format (and give it the ID 14). Spout assumes that ID 14 is "03/14/01" as it does not handle localized formats.
Fixing this issue is not a top priority so what you can do in the meantime is format the dates manually (don't use `setShouldFormatDates` and call `$date->format('dd/mm/yyyy')`).

Regarding dates with extra characters (`;@` in your case), I'll push a fix for that.

**Closed** 2016-10-18 18:55 UTC

**Comment by sangar82** [comment] 2016-10-19 07:31
Thanks for the extra characters fix!

I can't use format with the dates because I need to save the date in the same format that the user wrote the cell. After, with this date, the users will sent messages and need the same date to show (I can't show this format to spanish user (m/d/y) because it can lead to confusion).

I'm still investigating ...

**Comment by adrilo** [comment] 2016-10-19 16:43
If you use Excel to read the generated file, the date will be formatted differently, based on your OS settings. When I opened the file on my computer where dates are setup to be displayed as `mm/dd/yy`, "7/25/1982" was displayed. After changing the OS dates to be `dd/mm/yy` and re-opening the file in Excel, the date was displayed as "25/7/1982".

My point is that you cannot control what the user sees, as Excel will just pick the OS short date format to format the date.

**Comment by GerolamoAEdificari** [comment] 2017-07-14 12:36
I think the suggestion you made in [https://github.com/box/spout/issues/178](url) will be very much appreciated. Some xls/xlsx files use the 1904 date format instead of 1900 [https://support.microsoft.com/nl-nl/help/214330/differences-between-the-1900-and-the-1904-date-system-in-excel](url). When automatic date conversion can be disabled it's in the programmers hand to decide...
