### ISSUE TITLE
Segmentation fault with HHVM 3.10

### ISSUE THREAD

**Issue by anshu2212** [box/spout#166] opened 2016-01-12 12:18 UTC
I use Ubuntu prebuilt **hhvm** at a 2gb ram 1vcpu vps. I need to read some csv file so i found **Spout** from box claiming lowest memory usasge than phpexcel. but HHVM got segmentation fault . i was importing the file with phpmyadmin which usasge  **PHPExcel**.

My csv contains 6k rows with 15 columns. and it will increase in my application.

I tried to reduce the memory limit of hhvm and running from command line but none worked.

Message is:
`Core dumped: Segmentation fault`
`Stack trace in /tmp/stacktrace.12516.log`
`Segmentation fault`

and stack trace contains

`#0  feof(Resource id #4) called at [/home/<user>/public_html/grievance/Spout/Common/Helper/GlobalFunctionsHelper.php:215]`
`#1  Box\Spout\Common\Helper\GlobalFunctionsHelper->feof(Resource id #4) called at [/home/<user>/public_html/grievance/Spout/Reader/CSV/RowIterator.php:132]`
`#2  Box\Spout\Reader\CSV\RowIterator->next() called at [/home/<user>/public_html/grievance/test.php:47]`

**Comment by adrilo** [comment] 2016-01-12 19:35
HHVM 3.10

**Comment by anshu2212** [comment] 2016-01-12 19:44
yup

**Comment by adrilo** [comment] 2016-03-15 01:23
Hey @anshu2212, it seems like it may be caused by your code rather than Spout. Can you share the snipped where you parse the CSV?

**Comment by anshu2212** [comment] 2016-03-15 09:29
1. `require_once 'Spout/Autoloader/autoload.php';`
2. `use Box\Spout\Reader\ReaderFactory;`
3. `use Box\Spout\Common\Type;`
4. `$reader = ReaderFactory::create(Type::CSV);`
5. `$reader->open('/home/012016.csv');`
6. `echo '<table>';`
7. `foreach ($reader->getSheetIterator() as $sheet) {`
8. `	echo '<tbody>';`
9. `    foreach ($sheet->getRowIterator() as $key=>$row) {`
10. `        if($key==0){`
11. `			echo'<thead><tr>';`
12. `			foreach($row as $val){`
13. `				echo '<th>'.$val.'</th>';`
14. `			}`
15. `			echo '</tr></thead>';`
16. `		}else{`
17. `			echo '<tr>';`
18. `			foreach($row as $val){`
19. `				echo '<td>'.$val.'</td>';`
20. `			}`
21. `			echo '</tr>';`
22. `		}`
23. `    }`
24. `	echo '</tbody>';`
25. `}`
26. `echo '</table>';`

**Comment by anshu2212** [comment] 2016-03-15 09:30
@adrilo above code works perfect for php5 and php7

**Comment by adrilo** [comment] 2016-03-15 18:13
Your code looks good! Seems like the issue comes from your version HHVM (feof was fixed in v3.0.0).
At this point, you should check with the [HHVM](https://github.com/facebook/hhvm) team if this is something they know about.

Another option is to try upgrading HHVM to see if the issue is still there. You may also using a corrupted version of HHVM.

Closing the ticket, as there's nothing I can do to help you figure out what's wrong.

**Closed by adrilo** 2016-03-15 18:13 UTC
